spring.application.name: rtl-433-ingester
spring.profiles.active: ${PROFILE:local}

server.port: ${SERVER_PORT:4000}

info:
  app.name: ${spring.application.name}
  app.version: ${version:LOCAL}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

application.ingester:
  mqtt:
    client-id: rtl-433-ingester